#!/usr/bin/env perl

use strict;
use warnings;

BEGIN { $ENV{MT_HOME} or die "MT_HOME environment variable not set" }

use lib "$ENV{MT_HOME}/plugins/ConvertDB/lib";

$| = 1;

use MT::ConvertDB::CLI;
my $cli = MT::ConvertDB::CLI->new_with_options->run;
