#!/usr/bin/env perl -w
use strict;
use warnings;

BEGIN {
    $ENV{MT_HOME} or die "MT_HOME environment variable not set";
}

use lib "$ENV{MT_HOME}/addons/Enterprise.pack/lib",
        "$ENV{MT_HOME}/extlib",
        "$ENV{MT_HOME}/lib",
        "$ENV{MT_HOME}/plugins/ConvertDB/lib";

$| = 1;

use MT::ConvertDB::CLI;
MT::ConvertDB::CLI->run;
